pipeline {
    agent { label 'linux-node1' }

    stages {
        stage('User') {
            steps { sh 'whoami' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}