pipeline {
    agent { label 'linux-node1' }

    stages {
        stage('Hello') {
            steps { echo 'Hello, Jenkins Pipeline!' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}
