pipeline {
    agent any

    stages {
        stage('Date') {
            steps { sh 'date' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}