pipeline {
   agent { label 'linux-node1' }

    stages {
        stage('Hostname') {
            steps { sh 'hostname' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}