pipeline {
   agent { label 'linux-node1' }

    stages {
        stage('Build') {
            steps { echo 'Building...' }
        }
        stage('Test') {
            steps { echo 'Testing...' }
        }
        stage('Deploy') {
            steps { echo 'Deploying...' }
        }
    }

    post {
        always { 
            echo "Pipeline execution completed." 
            }
        success {
             echo "Pipeline executed successfully."
              }
        failure {
             echo "Pipeline execution failed."
              }
    }
}