pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps { echo 'Checkout stage' }
        }
        stage('Build') {
            steps { echo 'Build stage' }
        }
        stage('Test') {
            steps { echo 'Test stage' }
        }
        stage('Deploy') {
            steps { echo 'Deploy stage' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}