pipeline {
    agent { label 'linux-node1' }

    stages {
        stage('Script') {
            steps {
                sh '''
                echo "Running script"
                date
                '''
            }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}