pipeline {
    agent { label 'linux-node1' }

    stages {
        stage('Stage 1') {
            steps { echo 'First message' }
        }
        stage('Stage 2') {
            steps { echo 'Second message' }
        }
    }

    post {
        always { echo "Pipeline execution completed." }
        success { echo "Pipeline executed successfully." }
        failure { echo "Pipeline execution failed." }
    }
}